apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: derivatives
resources: [namespace.yaml, configmap.yaml, redis.yaml, marketdata.yaml, pricing.yaml, portfolio.yaml, hpa.yaml]
